spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${db.url:jdbc:mysql://localhost/serverapi}
      username: ${db.username:test}
      password: ${db.password:password}
  redis:
    host: redis
    port: 6379

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.zip"
      max-file-size: 500MB
      max-history: 90
  file:
    name: /log/server-api/serverapi.log
  level:
    root: info
    com.juno.appling: info