spring:
  profiles:
    active: ${server.profile:local}

logging:
  #  pattern:
  #    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    root: info
    ai.serverapi: info

server:
  port: 8000

api-prefix: /api

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWp1bm8tc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWp1bm8tYXBwbGluZwo=


--- # local
logging:
  #  pattern:
  #    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    root: info
    ai.serverapi: debug


spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:serverapi;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
  sql:
    init:
      data-locations: classpath:init.sql
  redis:
    host: localhost
    port: 6379


--- # dev
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${db.url:jdbc:mysql://localhost/serverapi}
      username: ${db.username:test}
      password: ${db.password:password}
  redis:
    host: localhost
    port: 6379

--- # prod
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${db.url:jdbc:mysql://localhost/serverapi}
      username: ${db.username:test}
      password: ${db.password:password}
  redis:
    host: redis
    port: 6379
